# permissions for end users to view commonevents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonevent-viewer-role
rules:
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - commonevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnosis.kubediag.org
  resources:
  - commonevents/status
  verbs:
  - get
