apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sonobuoy-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - /metrics
  - /logs
  - /logs/*
  verbs:
  - get
